version: '3'

services:
 web:
    build: ./docker-nginx
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./app
        - ./docker-nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./ssl:/etc/nginx/ssl