services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always
    environment:
      DOMAINS: "localhost.example.com -> http://web"
      STAGE: local
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "8081:8080"
